// clones the git dir
//
def clone_git_dir(git_url,directory,credentials){
    sh("sudo rm -rf $directory")
    sh("sudo mkdir -p $directory")
    sh("sudo chmod 777 $directory")
    dir("$directory")
    {
       // credentials id is generated by jenkins when you add a new credentials
       git url: "$git_url",credentialsId:"$credentials"
    }
}

// runs a script where we can grab output
def run_generic_script(){
   script_cmd = "${env.script_directory}/${env.script_name}" +
      " --arg1 ${env.script_option1} " +
      " --arg2 ${env.script_option2} " +
      " --arg3 ${env.script_option3}"
   script_output = write_script_to_file(script_cmd,"/tmp/cleanup.sh")
}

// run a script and return output
def run_script_with_output(script_cmd){
   return sh (script: "$script_cmd", returnStdout:true).trim()
}

// run a script and return status of cmd
def run_script(script_cmd){
   return_status = sh (script: "$script_cmd", returnStatus:true)
   return return_status
}

// run a script and return output
def write_script_to_file(script_cmd, file){
    sh ("echo \"$script_cmd\" > $file")
}

return this
